### ISSUE TITLE
IF git-paper > 404 results error

### ISSUE THREAD

**Issue by BaxAndrei** [Lenni0451/SpigotPluginManager#22] opened 2023-02-22 20:16 UTC
When I use /pm unload PLUgin still see it in /pl list also I used your API to auto-update my plugin and after paper 504 build it broke.

```
org.bukkit.command.CommandException: Unhandled exception executing command 'bxcore' in plugin Bx-Core v2.0.0-DEV-${BUILD_NUMBER}
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:912) ~[paper-1.19.3.jar:git-Paper-414]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchServerCommand(CraftServer.java:875) ~[paper-1.19.3.jar:git-Paper-414]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:501) ~[paper-1.19.3.jar:git-Paper-414]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:448) ~[paper-1.19.3.jar:git-Paper-414]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-414]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-414]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-414]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.UnsupportedOperationException
        at io.papermc.paper.plugin.manager.DummyBukkitPluginLoader.loadPlugin(DummyBukkitPluginLoader.java:30) ~[paper-1.19.3.jar:git-Paper-414]
        at net.lenni0451.spm.utils.PluginUtils.loadPlugin(PluginUtils.java:234) ~[PluginManager.jar:?]
        at ro.baxandrei.bxcore.utilitati.integrari.JenkinsUpdater.verificaActualizari(JenkinsUpdater.java:170) ~[Bx-Core-2.0.0-DEV-null.jar:?]
        at ro.baxandrei.bxcore.comenzi.BxCore.onCommand(BxCore.java:54) ~[Bx-Core-2.0.0-DEV-null.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        ... 9 more
```

```
// SAVE FILE from JENKINS

SpigotPluginManagerUtils.unloadPlugin(classPlugin);

                if (!classPlugin.getFile().delete()) {
                    Jucator.sendMessage(langWarningStergere);
                }

            if(SpigotPluginManagerUtils.loadPlugin(parseFileName(jenkinsAPI.artifacts.get(0).file)) == null) { <<-- ERROR LINE (JenkinsUpdater.java:170)
                Jucator.sendMessage(langEroareActivare);
                Jucator.playSound(sunetEroare);
                return;
            }
```

**Comment by Lenni0451** [comment] 2023-02-23 15:45
What server version are you using? Paper 1.19.3 is only at 418

**Comment by Lenni0451** [comment] 2023-02-23 15:58
I was able to reproduce the bug with paper 1.19.3-418. I am working on a fix...

**Comment by BaxAndrei** [comment] 2023-02-23 17:45
> What server version are you using? Paper 1.19.3 is only at 418

I meant 404, sorry

**Comment by Lenni0451** [comment] 2023-02-23 18:21
Wow, paper really rewrote the entire plugin loader. I now added support for it in commit  7d181a7be24465d27978275007e555a7b1c6b32.
I will also release a new version after doing some more stuff. Since you use the PluginUtils in your own plugin you are good to go.

**Comment by BaxAndrei** [comment] 2023-02-23 19:15
Yeah, they broke few other plugins on spigot marketplace. Ty very much <3 🍺

**Comment by BaxAndrei** [comment] 2023-02-23 19:38
If you want, I can provide you an outdated jar of my plugin to test with it the auto-update.

```
> pm unload bx-core
[21:35:31 INFO]: [Bx-Core] Disabling Bx-Core v2.0.0-DEV-602
[21:35:31 INFO]: PM | The plugin has been unloaded.
[21:35:31 WARN]: Can't keep up! Is the server overloaded? Running 6055ms or 121 ticks behind
> pl
[21:35:32 INFO]: Server Plugins (8):
[21:35:32 INFO]: Bukkit Plugins:
[21:35:32 INFO]:  - Essentials, EssentialsChat, EssentialsSpawn, LuckPerms, PluginManager, ShopGUIPlus, SkinsRestorer, Vault
> pm load bx-core
[21:35:35 ERROR]: [ModernPluginLoadingStrategy] Could not load '.\plugins\bx-core.jar' in '.\plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [Essentials, Vault]. Please download and install these plugins to run 'Bx-Core'.
```

```
> bxcore update
[21:37:37 INFO]: [BX] Se incepe procedura de actualizare a pluginului.
[21:37:38 INFO]: [Bx-Core] A fost descarcata versiunea Bx-Core-2.0.0-DEV-602.jar de pe server
[21:37:42 INFO]: [Bx-Core] Disabling Bx-Core v2.0.0-DEV-${BUILD_NUMBER}
[21:37:42 ERROR]: [ModernPluginLoadingStrategy] Could not load '.\plugins\Bx-Core.jar' in '.\plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [Essentials, Vault]. Please download and install these plugins to run 'Bx-Core'.
        at io.papermc.paper.plugin.entrypoint.strategy.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:76) ~[paper-1.19.3.jar:git-Paper-420]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:35) ~[paper-1.19.3.jar:git-Paper-420]
        at io.papermc.paper.plugin.manager.SingularRuntimePluginProviderStorage.enter(SingularRuntimePluginProviderStorage.java:63) ~[paper-1.19.3.jar:git-Paper-420]
        at io.papermc.paper.plugin.manager.RuntimePluginEntrypointHandler.enter(RuntimePluginEntrypointHandler.java:40) ~[paper-1.19.3.jar:git-Paper-420]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.loadPlugin(PaperPluginInstanceManager.java:121) ~[paper-1.19.3.jar:git-Paper-420]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.loadPlugin(PaperPluginManagerImpl.java:82) ~[paper-1.19.3.jar:git-Paper-420]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:406) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at net.lenni0451.spm.utils.PluginUtils.loadPlugin(PluginUtils.java:249) ~[PluginManager.jar:?]
        at ro.baxandrei.bxcore.utilitati.integrari.JenkinsUpdater.verificaActualizari(JenkinsUpdater.java:170) ~[Bx-Core.jar:?]
        at ro.baxandrei.bxcore.comenzi.BxCore.onCommand(BxCore.java:63) ~[Bx-Core.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:912) ~[paper-1.19.3.jar:git-Paper-420]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchServerCommand(CraftServer.java:875) ~[paper-1.19.3.jar:git-Paper-420]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:501) ~[paper-1.19.3.jar:git-Paper-420]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:448) ~[paper-1.19.3.jar:git-Paper-420]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-420]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-420]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-420]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
[21:37:42 WARN]: Unexpected exception while parsing console command "bxcore update"
org.bukkit.command.CommandException: Unhandled exception executing command 'bxcore' in plugin Bx-Core v2.0.0-DEV-${BUILD_NUMBER}
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:912) ~[paper-1.19.3.jar:git-Paper-420]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchServerCommand(CraftServer.java:875) ~[paper-1.19.3.jar:git-Paper-420]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:501) ~[paper-1.19.3.jar:git-Paper-420]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:448) ~[paper-1.19.3.jar:git-Paper-420]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-420]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-420]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-420]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.IllegalStateException: Invalid plugin file
        at net.lenni0451.spm.utils.PluginUtils.loadPlugin(PluginUtils.java:255) ~[PluginManager.jar:?]
        at ro.baxandrei.bxcore.utilitati.integrari.JenkinsUpdater.verificaActualizari(JenkinsUpdater.java:170) ~[Bx-Core.jar:?]
        at ro.baxandrei.bxcore.comenzi.BxCore.onCommand(BxCore.java:63) ~[Bx-Core.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        ... 9 more
```

```
> pm reload bx-core
[21:59:33 INFO]: [Bx-Core] Disabling Bx-Core v2.0.0-DEV-602
[21:59:33 ERROR]: [ModernPluginLoadingStrategy] Could not load '.\plugins\Bx-Core.jar' in '.\plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [Essentials, Vault]. Please download and install these plugins to run 'Bx-Core'.
        at io.papermc.paper.plugin.entrypoint.strategy.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:76) ~[paper-1.19.3.jar:git-Paper-420]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:35) ~[paper-1.19.3.jar:git-Paper-420]
        at io.papermc.paper.plugin.manager.SingularRuntimePluginProviderStorage.enter(SingularRuntimePluginProviderStorage.java:63) ~[paper-1.19.3.jar:git-Paper-420]
        at io.papermc.paper.plugin.manager.RuntimePluginEntrypointHandler.enter(RuntimePluginEntrypointHandler.java:40) ~[paper-1.19.3.jar:git-Paper-420]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.loadPlugin(PaperPluginInstanceManager.java:121) ~[paper-1.19.3.jar:git-Paper-420]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.loadPlugin(PaperPluginManagerImpl.java:82) ~[paper-1.19.3.jar:git-Paper-420]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:406) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at net.lenni0451.spm.utils.PluginUtils.loadPlugin(PluginUtils.java:249) ~[PluginManager.jar:?]
        at net.lenni0451.spm.utils.PluginUtils.loadPlugin(PluginUtils.java:213) ~[PluginManager.jar:?]
        at net.lenni0451.spm.commands.subs.Reload_Sub.execute(Reload_Sub.java:38) ~[PluginManager.jar:?]
        at net.lenni0451.spm.commands.PluginManager_Command.lambda$onCommand$0(PluginManager_Command.java:94) ~[PluginManager.jar:?]
        at net.lenni0451.spm.commands.PluginManager_Command.onCommand(PluginManager_Command.java:110) ~[PluginManager.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:731) ~[EssentialsX.jar:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:717) ~[EssentialsX.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:912) ~[paper-1.19.3.jar:git-Paper-420]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchServerCommand(CraftServer.java:875) ~[paper-1.19.3.jar:git-Paper-420]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:501) ~[paper-1.19.3.jar:git-Paper-420]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:448) ~[paper-1.19.3.jar:git-Paper-420]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-420]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-420]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-420]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
[21:59:33 WARN]: java.lang.IllegalStateException: Invalid plugin file
[21:59:33 WARN]:        at PluginManager.jar//net.lenni0451.spm.utils.PluginUtils.loadPlugin(PluginUtils.java:255)
[21:59:33 WARN]:        at PluginManager.jar//net.lenni0451.spm.utils.PluginUtils.loadPlugin(PluginUtils.java:213)
[21:59:33 WARN]:        at PluginManager.jar//net.lenni0451.spm.commands.subs.Reload_Sub.execute(Reload_Sub.java:38)
[21:59:33 WARN]:        at PluginManager.jar//net.lenni0451.spm.commands.PluginManager_Command.lambda$onCommand$0(PluginManager_Command.java:94)
[21:59:33 WARN]:        at PluginManager.jar//net.lenni0451.spm.commands.PluginManager_Command.onCommand(PluginManager_Command.java:110)
[21:59:33 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[21:59:33 WARN]:        at EssentialsX.jar//com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:731)
[21:59:33 WARN]:        at EssentialsX.jar//com.earth2me.essentials.Essentials.onCommand(Essentials.java:717)
[21:59:33 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[21:59:33 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[21:59:33 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:912)
[21:59:33 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchServerCommand(CraftServer.java:875)
[21:59:33 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.bg(DedicatedServer.java:501)
[21:59:33 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:448)
[21:59:33 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[21:59:33 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
[21:59:33 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[21:59:33 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
[21:59:33 INFO]: PM | Could not load the plugin Bx-Core. (Invalid plugin file)
```

**Comment by BaxAndrei** [comment] 2023-02-24 07:44
@Lenni0451 I managed to make my plugin auto-update again (temp solution) by removing everything from plugin.yml depend and moving to softdepend. Problem appear only when plugin that is reloaded has depend plugins.

**Comment by Lenni0451** [comment] 2023-02-24 09:56
I am unable to reproduce this. I was able to reload vault and a plugin by me depending on vault without any problems

**Comment by BaxAndrei** [comment] 2023-02-24 13:42
If you want I can send you the plugin jar to test with it

**Comment by Lenni0451** [comment] 2023-02-24 13:44
That would be helpful, thanks. I may not be able to fix this until Monday since I'm not at home...

**Comment by BaxAndrei** [comment] 2023-02-24 13:48
Can you please send me an email to contact@baxandrei.ro then I will send all files there? My project is not done yet and I don`t want to make it available thru github yet.

**Comment by BaxAndrei** [comment] 2023-02-24 13:53
Can you please send me an email to REDACTED then I will send all files there? My project is not done yet and I don`t want to make it available thru github yet.

**Comment by Lenni0451** [comment] 2023-02-26 19:28
I just looked a bit deeper into the paper code and it seems like there is nothing I can do about this. Paper expects all plugins and their dependencies to be loaded at the same time...
The same exception occurs if I try to reload EssentialsChat which has a hard dependency on Essentials. Reloading Essentials itself is fine because it has no hard dependencies on anything else

**Comment by BaxAndrei** [comment] 2023-02-27 07:30
I understand, thank you for your time and patience. In this case, I will remove the dependency and check directly in the code if the dependencies are loaded or not, so I can bypass the new "wonderful" changes.

```
this.getServer().getPluginManager().getPlugin("Essentials") == null || this.getServer().getPluginManager().getPlugin("Vault") == null
```

From what I understand, it is experimental and can be changed or even reverted.

**Comment by Lenni0451** [comment] 2023-02-27 08:20
I have started working on v3 of Plugin Manager. I am planning to fully support this paper change when I continue working on it. But don't expect this to happen any time soon. I work on my projects in my free time and have multiple projects I want to continue

**Comment by BaxAndrei** [comment] 2023-02-27 08:42
Great, I really appreciate what you are doing! You should put a donation link on the plugin page.

**Comment by Lenni0451** [comment] 2023-02-28 15:17
Thanks, but I don't think I will put up a donation link.
I will close this issue now since the original bug is fixed and I can't really do something with the paper load situation.

**Closed as completed by Lenni0451** 2023-02-28 15:17 UTC
Labels: bug
